//! The least-privilege RBAC the customer applies: one ServiceAccount, and in each allowed
//! namespace one Role with `get`, `list` and `watch` on the allowed kinds and nothing else,
//! bound to it. The agent prints it; it never applies it. No ClusterRole, no wildcard, no
//! secrets, no subresources, no write verb.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use super::kinds::{Kind, valid_name};
use crate::error::{Error, Result};

/// The only verbs ever generated.
pub const VERBS: [&str; 3] = ["get", "list", "watch"];

/// What to generate.
#[derive(Debug, Clone)]
pub struct Request<'a> {
    /// Namespaces the agent may read.
    pub namespaces: &'a [String],
    /// Kinds it may read in them.
    pub kinds: &'a [Kind],
    /// The ServiceAccount's name.
    pub account: &'a str,
    /// The namespace the ServiceAccount lives in (where the agent runs).
    pub account_namespace: &'a str,
}

/// The YAML for `req`.
///
/// # Errors
/// A name is not a valid Kubernetes name, or there is no namespace or kind.
pub fn generate(req: &Request<'_>) -> Result<String> {
    if req.namespaces.is_empty() {
        return Err(Error::Policy("name at least one namespace".into()));
    }
    if req.kinds.is_empty() {
        return Err(Error::Policy("name at least one kind".into()));
    }
    for n in req
        .namespaces
        .iter()
        .map(String::as_str)
        .chain([req.account, req.account_namespace])
    {
        if !valid_name(n) || n.len() > 63 {
            return Err(Error::Policy(format!("not a valid name: {n:?}")));
        }
    }
    let mut by_group: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
    let mut kinds = req.kinds.to_vec();
    kinds.sort();
    kinds.dedup();
    for k in &kinds {
        by_group.entry(k.group()).or_default().push(k.resource());
    }
    let mut namespaces: Vec<&str> = req.namespaces.iter().map(String::as_str).collect();
    namespaces.sort_unstable();
    namespaces.dedup();
    let role = format!("{}-read", req.account);
    let mut y = String::new();
    let _ = writeln!(
        y,
        "# Read-only access for the InOrbit agent's Kubernetes extension.\n\
         # Generated by `iohr-agent k8s rbac`; review it, then apply it yourself:\n\
         #   kubectl apply -f this-file.yaml\n\
         # Verbs: get, list, watch only. No secrets, config maps, exec, attach,\n\
         # port-forward, logs, proxies or tokens. Remove it with kubectl delete -f."
    );
    let labels = "  labels:\n    app.kubernetes.io/managed-by: customer\n    app.kubernetes.io/part-of: inorbit-agent\n";
    let _ = write!(
        y,
        "---\napiVersion: v1\nkind: ServiceAccount\nmetadata:\n  name: {}\n  namespace: {}\n{labels}automountServiceAccountToken: true\n",
        req.account, req.account_namespace
    );
    for ns in namespaces {
        let _ = write!(
            y,
            "---\napiVersion: rbac.authorization.k8s.io/v1\nkind: Role\nmetadata:\n  name: {role}\n  namespace: {ns}\n{labels}rules:\n"
        );
        for (group, resources) in &by_group {
            let _ = write!(
                y,
                "  - apiGroups: [\"{group}\"]\n    resources: [{}]\n    verbs: [{}]\n",
                resources
                    .iter()
                    .map(|r| format!("\"{r}\""))
                    .collect::<Vec<_>>()
                    .join(", "),
                VERBS
                    .iter()
                    .map(|v| format!("\"{v}\""))
                    .collect::<Vec<_>>()
                    .join(", ")
            );
        }
        let _ = write!(
            y,
            "---\napiVersion: rbac.authorization.k8s.io/v1\nkind: RoleBinding\nmetadata:\n  name: {role}\n  namespace: {ns}\n{labels}roleRef:\n  apiGroup: rbac.authorization.k8s.io\n  kind: Role\n  name: {role}\nsubjects:\n  - kind: ServiceAccount\n    name: {}\n    namespace: {}\n",
            req.account, req.account_namespace
        );
    }
    Ok(y)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn all() -> String {
        generate(&Request {
            namespaces: &["shop".into(), "payments".into()],
            kinds: &Kind::ALL,
            account: "iohr-k8s-reader",
            account_namespace: "inorbit",
        })
        .unwrap()
    }

    #[test]
    fn only_get_list_watch_on_the_allowed_kinds() {
        let y = all();
        for bad in [
            "secrets",
            "configmaps",
            "exec",
            "attach",
            "portforward",
            "proxy",
            "pods/log",
            "\"*\"",
            "create",
            "update",
            "patch",
            "delete",
            "deletecollection",
            "escalate",
            "bind",
            "impersonate",
            "ClusterRole",
        ] {
            assert!(!y.contains(bad), "the RBAC contains {bad}");
        }
        assert_eq!(y.matches("kind: Role\n").count(), 2);
        assert_eq!(y.matches("kind: RoleBinding\n").count(), 2);
        assert_eq!(
            y.matches("verbs: [\"get\", \"list\", \"watch\"]").count(),
            4
        );
        assert!(y.contains(
            "resources: [\"deployments\", \"statefulsets\", \"daemonsets\", \"replicasets\"]"
        ));
        assert!(y.contains("resources: [\"pods\", \"events\"]"));
    }

    #[test]
    fn it_parses_as_yaml_documents_scoped_to_the_namespaces() {
        let y = all();
        let mut n = 0;
        for doc in serde_yaml_ng::Deserializer::from_str(&y) {
            let v: serde_json::Value = serde::Deserialize::deserialize(doc).unwrap();
            n += 1;
            let kind = v["kind"].as_str().unwrap();
            let ns = v["metadata"]["namespace"].as_str().unwrap();
            match kind {
                "ServiceAccount" => assert_eq!(ns, "inorbit"),
                "Role" | "RoleBinding" => assert!(ns == "shop" || ns == "payments"),
                other => panic!("unexpected {other}"),
            }
        }
        assert_eq!(n, 5);
    }

    #[test]
    fn bad_names_and_empty_requests_are_refused() {
        let k = [Kind::Pods];
        for (ns, acct) in [
            (vec!["Shop".to_owned()], "a"),
            (vec!["shop; rm".to_owned()], "a"),
            (vec!["shop".to_owned()], "a\nkind: ClusterRole"),
            (vec![], "a"),
        ] {
            assert!(
                generate(&Request {
                    namespaces: &ns,
                    kinds: &k,
                    account: acct,
                    account_namespace: "x"
                })
                .is_err()
            );
        }
        assert!(
            generate(&Request {
                namespaces: &["a".into()],
                kinds: &[],
                account: "a",
                account_namespace: "x"
            })
            .is_err()
        );
    }
}
