apiVersion: v2
name: iohr-agent
description: >-
  The InOrbit agent. Dials out to the platform, obeys a local policy, runs
  checks in your cluster's network.
type: application
version: 0.1.0-alpha.8
appVersion: 0.1.0-alpha.8
home: https://github.com/inorbithr/dataplane
sources:
  - https://github.com/inorbithr/dataplane
maintainers:
  - name: InOrbit d.o.o.
    url: https://inorbit.hr
annotations:
  artifacthub.io/license: Apache-2.0
